# Generated by Django 6.0.2 on 2026-04-27 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Refill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tb_cascade_status', models.CharField(blank=True, choices=[('Presumptive', 'Presumptive'), ('Confirmed', 'Confirmed'), ('Negative', 'Negative')], max_length=50, null=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('last_pickup_date', models.DateField(blank=True, null=True)),
                ('months_of_refill_days', models.DecimalField(decimal_places=2, max_digits=4)),
                ('current_regimen', models.CharField(max_length=255)),
                ('case_manager', models.CharField(max_length=255)),
                ('remark', models.TextField(blank=True, null=True)),
                ('current_art_status', models.CharField(choices=[('Active', 'Active'), ('Active Restart', 'Active Restart'), ('Restart', 'Restart'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('next_appointment', models.DateField(blank=True, null=True)),
                ('expected_iit_date', models.DateField(blank=True, null=True)),
                ('missed_appointment', models.BooleanField(default=False)),
                ('art_start_date', models.DateField(blank=True, null=True)),
                ('vl_sample_collection_date', models.DateField(blank=True, null=True)),
                ('vl_result', models.IntegerField(blank=True, null=True)),
                ('tpt_start_date', models.DateField(blank=True, null=True)),
                ('tpt_completion_date', models.DateField(blank=True, null=True)),
                ('tpt_expected_completion', models.DateField(blank=True, null=True)),
                ('eac_start_date', models.DateField(blank=True, null=True)),
                ('eac_sessions_completed', models.IntegerField(default=0)),
                ('tb_screening_date', models.DateField(blank=True, null=True)),
                ('tb_screening_type', models.CharField(blank=True, choices=[('Symptom Screening', 'Symptom Screening'), ('Chest X-ray', 'Chest X-ray'), ('GeneXpert', 'GeneXpert'), ('LAM', 'LAM')], max_length=50, null=True)),
                ('tb_status', models.CharField(blank=True, choices=[('No TB Symptoms', 'No TB Symptoms'), ('Presumptive TB', 'Presumptive TB'), ('TB Confirmed', 'TB Confirmed')], max_length=50, null=True)),
                ('tb_sample_collection_date', models.DateField(blank=True, null=True)),
                ('tb_result_received_date', models.DateField(blank=True, null=True)),
                ('tb_diagnostic_result', models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Indeterminate', 'Indeterminate')], max_length=50, null=True)),
                ('tracking_date_1', models.DateField(blank=True, null=True)),
                ('tracking_date_2', models.DateField(blank=True, null=True)),
                ('tracking_date_3', models.DateField(blank=True, null=True)),
                ('tracked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_discontinued', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('discontinued_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('discontinued_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refills', to='refills.facility')),
            ],
            options={
                'ordering': ['facility__name', '-last_pickup_date'],
            },
        ),
    ]
