# Generated by Django 6.0.2 on 2026-05-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='missed_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
