# Generated by Django 6.0.2 on 2026-03-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='tb_cascade_status',
            field=models.CharField(blank=True, choices=[('Presumptive', 'Presumptive'), ('Confirmed', 'Confirmed'), ('Negative', 'Negative')], max_length=50, null=True),
        ),
    ]
