# Generated by Django 6.0.2 on 2026-04-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refill',
            name='discontinued_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
