# Generated by Django 6.0.2 on 2026-03-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refills', '0002_refill_tb_cascade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='discontinued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refill',
            name='discontinued_reason',
            field=models.CharField(blank=True, choices=[('Transferred Out', 'Transferred Out'), ('Death', 'Death')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='refill',
            name='patient_discontinued',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='refill',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refill',
            name='tracked_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='refill',
            name='tracking_date_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refill',
            name='tracking_date_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refill',
            name='tracking_date_3',
            field=models.DateField(blank=True, null=True),
        ),
    ]
