# Generated by Django 6.0.2 on 2026-04-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refills', '0002_alter_refill_discontinued_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refill',
            options={'ordering': ['facility__name', '-last_pickup_date']},
        ),
        migrations.AlterUniqueTogether(
            name='refill',
            unique_together=set(),
        ),
    ]
