# Generated by Django 6.0.2 on 2026-02-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refills', '0005_rename_viral_load_sample_date_refill_vl_sample_collection_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='refill',
            name='refills_ref_facilit_26db0f_idx',
        ),
        migrations.RemoveIndex(
            model_name='refill',
            name='refills_ref_next_ap_a7555c_idx',
        ),
        migrations.RemoveIndex(
            model_name='refill',
            name='refills_ref_last_pi_62dc4b_idx',
        ),
        migrations.AddField(
            model_name='refill',
            name='tpt_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refill',
            name='tpt_expected_completion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refill',
            name='tpt_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
