# Generated by Django 6.0.2 on 2026-03-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refills', '0006_remove_refill_refills_ref_facilit_26db0f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='eac_sessions_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refill',
            name='eac_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
