# Generated by Django 6.0.2 on 2026-03-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refills', '0007_refill_eac_sessions_completed_refill_eac_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refill',
            name='current_art_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Active Restart', 'Active Restart'), ('Restart', 'Restart'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
