# Generated by Django 6.0.2 on 2026-03-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refills', '0009_refill_age_refill_tb_diagnostic_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refill',
            name='current_art_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Active Restart', 'Active Restart'), ('Restart', 'Restart'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='refill',
            name='tb_diagnostic_result',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Indeterminate', 'Indeterminate')], max_length=50, null=True),
        ),
    ]
